parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.

    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3307
    database_name: sylius
    database_user: sprint_config_test%kernel.environment%
    database_password: null
    phpcr_user: root
    phpcr_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: EDITME
    locale: en_US
    currency: USD
    wkhtmltopdf.bin_path: /usr/bin/wkhtmltopdf
    wkhtmltoimage.bin_path: /usr/bin/wkhtmltoimage
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: UTF8

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
